Add controller book and author
Andrey1916/BookStoreAPI-Dima pull request #1
Opened 2022-11-16 21:02 UTC by Dimitroll-GIT

Add controller book and author. Also add models.

2022-11-16 21:17 UTC, Andrey1916 requested changes

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Controllers/AuthorController.cs
> +        if (author.Surname.Length <= 2) return BadRequest("Surname must contain two or more leters");
Добавь вигурные скобки

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Controllers/BookController.cs
> +    {
Return specific status code when you do not found the book

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Controllers/BookController.cs
> +    {
Use `IActionResult<Book>`

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Controllers/BookController.cs
> +    {
https://learn.microsoft.com/ru-ru/aspnet/core/web-api/action-return-types?view=aspnetcore-7.0

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Models/Author.cs
> +{
Try to use file scoped namespace

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Models/Book.cs
> +        public string? Date { get; set; }
Use DateTime struct for date fields

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Models/Book.cs
> +        public string? Name { get; set; }
Why name is nullable field? Book must have Name

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Models/Book_Order.cs
> +        public int Orfer_id { get; set; }
"Orfer" -> "Order" 
Use camel case in your code

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Repositories/AuthorRepositories.cs
> +        => _authors.FirstOrDefault(item =>item.Id == id);
Lose space :)

2022-11-16 21:17 UTC, Andrey1916 commented on WebApplication1/Repositories/AuthorRepositories.cs
> +
Remove useless space

2022-11-17 16:11 UTC, Andrey1916 requested changes

2022-11-17 16:42 UTC, Dimitroll-GIT commented on WebApplication1/Models/Book.cs
> +    public string? Author { get; set; }
It will be fixed when i little rework database, whereupon fix models. Add/remove some field, and change data type.

2022-11-19 07:22 UTC, Andrey1916 approved these changes

2022-11-19 07:22 UTC, merged